# Generated by Django 6.0.5 on 2026-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.TextField(default="test1"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=models.CharField(max_length=300),
        ),
    ]
